from dash import html, dcc, Dash, Input, Output
import pandas as pd
import plotly.express as px
#Initialise App/Load Data
app = Dash(__name__)
df = pd.read_csv('Formattedoutput.csv')
df['date'] = pd.to_datetime(df['date'], format='mixed')
df = df.sort_values(by='date')

#Webpage Layout
app.layout = html.Div(
    style={'backgroundColor':"#414F63",'padding':'40px','minHeight':'100vh'},
    children=[
        html.H1(
            'Pink Morsel Sales Dashboard',
            style={'textAlign':'center', 'fontFamily':'Arial', 'color' : "#5C95E0" },
        ),



        dcc.RadioItems(
            id='region-filter',
            options=[
                {'label':'All Regions', 'value':'all'},
                {"label": "North", "value": "north"},
                {"label": "South", "value": "south"},
                {"label": "East", "value": "east"},
                {"label": "West", "value": "west"},
            ],
            value='all'
        ),

        dcc.Graph(id='sales-line-chart')        
    ]

)

@app.callback(
    Output('sales-line-chart', 'figure'),
    Input('region-filter','value'),
)

def update_graph(selected_region):

    if selected_region == 'all':
        filtered_df = df
    else:

        filtered_df = df[df['region']==selected_region]

    fig = px.line(
        filtered_df, x='date', y='sales', color='region', title='Sales Generated by Date'
    )

    return fig

if __name__ == '__main__':
    app.run(debug=True)
        